version: "3.8"
services:
  maven:
    image: maven:3.8-eclipse-temurin-11
    volumes:
      - .:/app
    working_dir: /app
    command: mvn clean package

  backend:
    build: .
    ports:
      - "8080:8080" # server app
      - "8000:8000" # debug
    depends_on:
      - maven
